#!/bin/bash
filename=$(basename -- "$1")
extension="${filename##*.}"
filename="${filename%.*}"
[ ! -d bin ] && mkdir bin
[ -f $1 ] && set -x && g++ $1 -std=c++2a -ggdb -Og -lbenchmark -lgtest -lpthread -fsanitize=address,undefined -o ./bin/$filename && ./bin/$filename
