#!/bin/bash
BASE=volume1/git

show_help()
{
	echo "show: list git repo"
	echo "create: create bare repo on server and clone"
	echo "clone: clone repo from server"
	echo "link: link current directory to server repo"
	exit 1
}

KEY="$1"
REPO="$2"
shift && shift

case $KEY in
	show)
		ssh router ls -C --ignore="#*" --ignore="@*" /$BASE
		;;
	create)
		if [ -d $REPO ]; then
			echo "repo directory exists!"
			exit 1
		fi
		ssh router git init --bare /$BASE/$REPO
		git clone ssh://router/$BASE/$REPO
		;;
	clone)
		git clone ssh://router/$BASE/$REPO
		;;
	link)
		[ ! -d .git ] && git init .
		git remote set-url origin ssh://router/$BASE/$REPO
		;;
	*)
		show_help
		;;
esac
