#!/bin/sh

case $1 in
	# DVI-I-1 connected to 2713H
	0) MONITOR="DVI-I-1" && ORIENTATION="left";;
	1) MONITOR="DVI-D-0" && ORIENTATION="left";;
	*) echo "Invalid monitor id!" && exit 1;;
esac

# Get current orientation
xrandr | grep "$MINOTR.*$ORIENTATION (" > /dev/null
# If rotated, go back to normal
if [ $? -eq 0 ]; then
	if [ $1 -eq 0 ]; then
		ORIENTATION="normal"
	else
		ORIENTATION="inverted"
	fi
fi

case $2 in
	0) ORIENTATION="normal";;
	90) ORIENTATION="left";;
	180) ORIENTATION="inverted";;
	270) ORIENTATION="right";;
esac

xrandr --output $MONITOR --rotate $ORIENTATION
