#!/bin/sh
find -name "*.c"    > ./cscope.files
find -name "*.cpp" >> ./cscope.files
find -name "*.cxx" >> ./cscope.files
find -name "*.cc " >> ./cscope.files
find -name "*.h"   >> ./cscope.files
find -name "*.hpp" >> ./cscope.files
find -name "*.hxx" >> ./cscope.files
find -name "*.hh " >> ./cscope.files
find -name "*.java" >> ./cscope.files
find -name "*.py"   >> ./cscope.files
cscope -bq
ctags --c++-kinds=+l+p+x+c+d+e+f+g+m+n+s+t+u+v --fields=+afiklsSt --extra=+q -n -R -L ./cscope.files
rm ./cscope.files
