#!/bin/sh
FILE_LIST=./cscope.files

add_c_files()
{
	find $1 -name "*.c"   >> $FILE_LIST
	find $1 -name "*.h"   >> $FILE_LIST
	find $1 -name "*.s"   >> $FILE_LIST
	find $1 -name "*.S"   >> $FILE_LIST
}

add_cpp_files()
{
	find $1 -name "*.cpp" >> $FILE_LIST
	find $1 -name "*.cxx" >> $FILE_LIST
	find $1 -name "*.cc " >> $FILE_LIST
	find $1 -name "*.hpp" >> $FILE_LIST
	find $1 -name "*.hxx" >> $FILE_LIST
	find $1 -name "*.hh " >> $FILE_LIST
}

kernel()
{
	make O=. cscope
	make O=. tags
}

if [ -f arch/x86/kernel/apic/x2apic.h ]; then
	kernel
else
	[ -f $FILE_LIST ] && rm $FILE_LIST
	touch $FILE_LIST
	add_c_files
	add_cpp_files
	find -name "*.java" >> $FILE_LIST
	find -name "*.py"   >> $FILE_LIST
	cscope -bq
	ctags --c++-kinds=+l+p+x+c+d+e+f+g+m+n+s+t+u+v --fields=+afiklsSt --extra=+q -n -R -L ./cscope.files
	[ -f $FILE_LIST ] && rm $FILE_LIST
fi
