#!/bin/bash
YCM=/usr/local/etc/vim/plugged/YouCompleteMe

need_recompile_ycm()
{
	[ ! -f $YCM/third_party/ycmd/ycm_core.so ] && return 0
	if [ -d $YCM ]; then
		cd $YCM
		git fetch origin
		DIFFS=`git rev-list HEAD...origin/master --count`
		[ $DIFFS -ne 0 ] && return 0
	else
		return 0
	fi
	return 1
}

need_recompile_ycm
RECOMPILE_YCM=$?
SHELL=/bin/bash vim +PlugUpdate +PlugUpgrade +qall

[ $RECOMPILE_YCM -eq 1 ] && exit 0
CMD="python3 $YCM/install.py --clang-completer --system-libclang"
which go && CMD+=" --gocode-completer"
which npm && CMD+=" --tern-completer"
eval $CMD
